# Generated by Django 4.2.30 on 2026-09-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionSunat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sunat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado SUNAT')),
                ('codigo_respuesta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Respuesta')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de SUNAT')),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Validación')),
                ('respuesta_sunat', models.JSONField(blank=True, default=dict, verbose_name='Respuesta Completa de SUNAT (JSON)')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='comprobantes.comprobante', verbose_name='Comprobante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó la Validación')),
            ],
            options={
                'verbose_name': 'Validación SUNAT',
                'verbose_name_plural': 'Validaciones SUNAT',
                'ordering': ['-fecha_validacion'],
                'indexes': [models.Index(fields=['comprobante'], name='validacione_comprob_20c6e8_idx'), models.Index(fields=['fecha_validacion'], name='validacione_fecha_v_ad3891_idx')],
            },
        ),
    ]
