# Generated by Django 4.2.30 on 2026-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TRABAJADOR', 'Trabajador')], default='TRABAJADOR', max_length=20, verbose_name='Rol en el Sistema'),
        ),
    ]
