# Generated by Django 4.2.30 on 2026-09-21 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_emisor', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe tener 11 dígitos numéricos.')], verbose_name='RUC Emisor')),
                ('tipo_comprobante', models.CharField(choices=[('03', '03 - Boleta de Venta Electrónica'), ('01', '01 - Factura Electrónica'), ('07', '07 - Nota de Crédito'), ('08', '08 - Nota de Débito')], default='03', max_length=2, verbose_name='Tipo de Comprobante')),
                ('serie', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[B|F|E][A-Z0-9]{3}$', 'Serie alfanumérica de 4 caracteres (ej. B001, F001, EB01).')], verbose_name='Serie')),
                ('numero', models.PositiveIntegerField(verbose_name='Número Correlativo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado'), ('ERROR_CONSULTA', 'Error de Consulta')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('tipo_documento_receptor', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo Doc. Receptor')),
                ('numero_documento_receptor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Doc. Receptor')),
                ('denominacion_receptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social / Nombre Receptor')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_emision', '-id'],
                'indexes': [models.Index(fields=['ruc_emisor', 'tipo_comprobante', 'serie', 'numero'], name='comprobante_ruc_emi_0192bb_idx'), models.Index(fields=['estado'], name='comprobante_estado_6c1c37_idx'), models.Index(fields=['fecha_emision'], name='comprobante_fecha_e_698c03_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.UniqueConstraint(fields=('ruc_emisor', 'tipo_comprobante', 'serie', 'numero'), name='unique_comprobante_ruc_tipo_serie_numero'),
        ),
    ]
