# Generated by Django 4.2.30 on 2026-09-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/', verbose_name='Archivo')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('cantidad_registros', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Registros')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('detalle_resultado', models.JSONField(blank=True, default=dict, verbose_name='Detalle del Resultado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_importacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'verbose_name_plural': 'Lotes de Importación',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
