# Generated by Django 4.2.30 on 2026-09-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteimportacion',
            name='cantidad_registros',
        ),
        migrations.RemoveField(
            model_name='loteimportacion',
            name='detalle_resultado',
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='duplicados_detalle',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle de Duplicados'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='errores_detalle',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle de Errores'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='importados_correctos',
            field=models.PositiveIntegerField(default=0, verbose_name='Importados Correctamente'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='total_duplicados',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Duplicados'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='total_errores',
            field=models.PositiveIntegerField(default=0, verbose_name='Total con Errores'),
        ),
        migrations.AddField(
            model_name='loteimportacion',
            name='total_leidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Leído'),
        ),
        migrations.AlterField(
            model_name='loteimportacion',
            name='archivo',
            field=models.FileField(upload_to='importaciones/%Y/%m/', verbose_name='Archivo Subido'),
        ),
        migrations.AlterField(
            model_name='loteimportacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error en la Carga')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='loteimportacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_importacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó la Carga'),
        ),
    ]
