# Generated by Django 4.2.30 on 2026-09-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('PDF', 'PDF (.pdf)')], max_length=10, verbose_name='Tipo de Reporte')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Nombre del Reporte')),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict, verbose_name='Filtros Aplicados')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/', verbose_name='Archivo Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
