# Generated by Django 4.2.30 on 2026-09-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('objeto_afectado', models.CharField(max_length=255, verbose_name='Objeto Afectado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Origen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario'], name='auditoria_r_usuario_5ab20b_idx'), models.Index(fields=['accion'], name='auditoria_r_accion_dae68a_idx'), models.Index(fields=['fecha'], name='auditoria_r_fecha_ee69fc_idx')],
            },
        ),
    ]
