# Generated by Django 6.1.1 on 2026-09-22 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='id_objeto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Objeto'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='resultado',
            field=models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('FALLIDO', 'Fallido'), ('ADVERTENCIA', 'Advertencia')], default='EXITOSO', max_length=50, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(help_text='Identificador normalizado de la acción realizada', max_length=100, verbose_name='Acción'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['resultado'], name='auditoria_r_resulta_062cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['id_objeto'], name='auditoria_r_id_obje_35ea9a_idx'),
        ),
    ]
